/**
 * Copies the canonical recording types from the extension into the viewer's
 * generated directory so the two projects stay in sync automatically.
 *
 * Usage: node scripts/sync-types.mjs
 *
 * The shared trigger/intervention vocabulary consts live directly in
 * recording/types.ts (self-contained, no '@extension/...' imports), so the file
 * is copied through verbatim. As a guard, the script fails fast if the source
 * ever (re-)introduces an '@extension/...' alias import — the viewer cannot
 * resolve path aliases, so an unresolved import must never reach the generated
 * file silently.
 */

import { readFileSync, writeFileSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const SOURCE = join(__dirname, '..', '..', 'extension', 'src', 'extension', 'services', 'recording', 'types.ts');
const DEST = join(__dirname, '..', 'src', 'generated', 'recordingTypes.ts');

const HEADER = `// DO NOT EDIT — auto-generated by sync-types.mjs
// Source: extension/src/extension/services/recording/types.ts
`;

let source = readFileSync(SOURCE, 'utf-8');

// Strip the leading JSDoc file header comment (/** ... */) if present
source = source.replace(/^\/\*\*[\s\S]*?\*\/\s*/, '');

// Guard: any surviving '@extension/...' import (default, named, type-only,
// or side-effect; single- or double-quoted) would be unresolvable in the
// viewer build. The vocabulary must stay inline in recording/types.ts.
const ALIAS_IMPORT_RE = /^import\b[^\n]*['"]@extension\/[^'"]+['"];/m;
const aliasImport = source.match(ALIAS_IMPORT_RE);
if (aliasImport) {
    console.error(
        `sync-types: ERROR — recording/types.ts contains an '@extension/...' import that the\n` +
        `viewer cannot resolve:\n  ${aliasImport[0]}\n` +
        `Inline the referenced declarations into recording/types.ts so the generated file stays self-contained.`
    );
    process.exit(1);
}

writeFileSync(DEST, HEADER + source, 'utf-8');
console.log(`Synced recording types → ${DEST}`);
