/**
 * Copies the canonical recording types from the extension into the viewer's
 * generated directory so the two projects stay in sync automatically.
 *
 * Usage: node scripts/sync-types.mjs
 *
 * If the source file imports shared vocabulary from '@extension/services/telemetry/types',
 * the import block is replaced with inlined const+type pairs so the generated file
 * stays self-contained (the viewer cannot resolve '@extension/...' path aliases).
 */

import { readFileSync, writeFileSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const SOURCE = join(__dirname, '..', '..', 'extension', 'src', 'extension', 'services', 'telemetry', 'recording', 'types.ts');
const VOCAB_SOURCE = join(__dirname, '..', '..', 'extension', 'src', 'extension', 'services', 'telemetry', 'types.ts');
const DEST = join(__dirname, '..', 'src', 'generated', 'recordingTypes.ts');

const HEADER = `// DO NOT EDIT — auto-generated by sync-types.mjs
// Source: extension/src/extension/services/telemetry/recording/types.ts
`;

let source = readFileSync(SOURCE, 'utf-8');

// Strip the leading JSDoc file header comment (/** ... */) if present
source = source.replace(/^\/\*\*[\s\S]*?\*\/\s*/, '');

// Detect an import block from '@extension/services/telemetry/types' and inline it
const EXTENSION_IMPORT_RE = /^import type \{([^}]+)\} from '@extension\/services\/telemetry\/types';/m;
const match = source.match(EXTENSION_IMPORT_RE);

if (match) {
    const importedNames = match[1]
        .split(',')
        .map(n => n.trim())
        .filter(Boolean);

    const vocab = readFileSync(VOCAB_SOURCE, 'utf-8');

    const inlinedPairs = [];

    for (const name of importedNames) {
        // Find: export type X = typeof CONST[number];
        const typeLineRe = new RegExp(`^export type ${name} = typeof (\\w+)\\[number\\];`, 'm');
        const typeMatch = vocab.match(typeLineRe);
        if (!typeMatch) {
            console.error(`sync-types: ERROR — could not find "export type ${name}" in ${VOCAB_SOURCE}`);
            process.exit(1);
        }
        const constName = typeMatch[1];

        // Find: export const CONST = [...] as const;  (may span multiple lines)
        const constRe = new RegExp(`(export const ${constName} = \\[.*?\\] as const;)`, 's');
        const constMatch = vocab.match(constRe);
        if (!constMatch) {
            console.error(`sync-types: ERROR — could not find "export const ${constName}" in ${VOCAB_SOURCE}`);
            process.exit(1);
        }

        inlinedPairs.push(constMatch[1]);
        inlinedPairs.push(`export type ${name} = typeof ${constName}[number];`);
    }

    const inlinedBlock =
        `// ── Inlined from extension/src/extension/services/telemetry/types.ts ──\n` +
        `// (sync-types.mjs resolves the @extension import by inlining the shared\n` +
        `//  vocabulary so the generated file stays self-contained)\n` +
        inlinedPairs.join('\n');

    source = source.replace(match[0], inlinedBlock);
}

writeFileSync(DEST, HEADER + source, 'utf-8');
console.log(`Synced recording types → ${DEST}`);
