/**
 * Copies the canonical recording types from the extension into the viewer's
 * generated directory so the two projects stay in sync automatically.
 *
 * Usage: node scripts/sync-types.mjs
 */

import { readFileSync, writeFileSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const SOURCE = join(__dirname, '..', '..', 'extension', 'src', 'extension', 'services', 'telemetry', 'recording', 'types.ts');
const DEST = join(__dirname, '..', 'src', 'generated', 'recordingTypes.ts');

const HEADER = `// DO NOT EDIT — auto-generated by sync-types.mjs
// Source: extension/src/extension/services/telemetry/recording/types.ts
`;

let source = readFileSync(SOURCE, 'utf-8');

// Strip the leading JSDoc file header comment (/** ... */) if present
source = source.replace(/^\/\*\*[\s\S]*?\*\/\s*/, '');

writeFileSync(DEST, HEADER + source, 'utf-8');
console.log(`Synced recording types → ${DEST}`);
