export { ChatContextManager } from './chat/chatContextManager';
export { ChatDiagnosticsService } from './chat/chatDiagnosticsService';
export { ChatMessageService } from './chat/chatMessageService';
export { IrisChatSessionService } from './chat/chatSessionService';
export { IrisWebSocketSessionClient } from './transport/irisWebSocketSessionClient';
export { IrisWebSocketMessageHandler } from './chat/irisWebSocketMessageHandler';
export type { IrisServiceDeps } from './context/sessionSyncUtils';
export { IRIS_CHAT_HELP_MARKDOWN } from './chat/helpContent';
export { ContextStore } from './context/contextStore';
export type { ChatContextReason } from './chat/chatContextManager';
